// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3pfsDVhjVXTAMRzd6_Qsv77uICRZaENw',
    appId: '1:297860711028:web:d3e4069d295767497c8721',
    messagingSenderId: '297860711028',
    projectId: 'todos-a044d',
    authDomain: 'todos-a044d.firebaseapp.com',
    storageBucket: 'todos-a044d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_q-5IZUxnBUSx9BQ-R2A54cxUJGjP1vM',
    appId: '1:297860711028:android:b3e59bef7fdf287c7c8721',
    messagingSenderId: '297860711028',
    projectId: 'todos-a044d',
    storageBucket: 'todos-a044d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKlzKPi61wUOzSWBXCCWrXaqohH7ZJ4bs',
    appId: '1:297860711028:ios:307eb8637288bd837c8721',
    messagingSenderId: '297860711028',
    projectId: 'todos-a044d',
    storageBucket: 'todos-a044d.appspot.com',
    iosClientId: '297860711028-h72319hrdee2nt25u2parkb05196sv30.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKlzKPi61wUOzSWBXCCWrXaqohH7ZJ4bs',
    appId: '1:297860711028:ios:307eb8637288bd837c8721',
    messagingSenderId: '297860711028',
    projectId: 'todos-a044d',
    storageBucket: 'todos-a044d.appspot.com',
    iosClientId: '297860711028-h72319hrdee2nt25u2parkb05196sv30.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFlutter',
  );
}
